GET http://localhost:8000/categories?page=1

###


GET http://localhost:8000/categories/03ccd350-fffd-4194-ada4-8ff77e0e0399

###


POST http://localhost:8000/categories
Content-Type: application/json

{
  "name": "movie"
}


###


PUT http://localhost:8000/categories/03ccd350-fffd-4194-ada4-8ff77e0e0399
Content-Type: application/json

{
  "name": "movie 2",
  "description": "movie 2 description"
}

###

DELETE http://localhost:8000/categories/03ccd350-fffd-4194-ada4-8ff77e0e0399
