GET http://localhost:8000/categories?page=1

###


GET http://localhost:8000/categories

###


POST http://localhost:8000/categories
Content-Type: application/json

{
  "name": "movie"
}


###


PUT http://localhost:8000/categories/db1ff133-6e3e-439b-add7-fa5b9eeb1a28
Content-Type: application/json

{
  "name": "movie 2",
  "description": "movie 2 description"
}

###

DELETE http://localhost:8000/categories/9966ceff-aa8a-467d-83c0-075dbad05907
