# Generated by Django 5.1.1 on 2024-10-02 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorymodel",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="categorymodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="id",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="categorymodel",
            table="categories",
        ),
    ]
