# Generated by Django 5.1.1 on 2024-10-04 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_app",
            "0002_categorymodel_created_at_categorymodel_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorymodel",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
